// WARNING: This file is automatically generated, do not manually modify.
import { withQuery } from 'ufo'
import type { DataLayer } from 'third-party-capital'
import { useRegistryScript } from '#nuxt-scripts-utils'
import type { RegistryScriptInput } from '#nuxt-scripts'
import { object, string, optional } from '#nuxt-scripts-validator'

export const GoogleAnalyticsOptions = object({
  id: string(),
  l: optional(string()),
})
export type GoogleAnalyticsInput = RegistryScriptInput<typeof GoogleAnalyticsOptions>

function use(options: GoogleAnalyticsInput) {
  return { dataLayer: (window as any)[options.l!] as DataLayer,
    gtag(...args: any) { ((window as any)[options.l!] as DataLayer).push(args) } }
}

export function useScriptGoogleAnalytics(_options?: GoogleAnalyticsInput) {
  return useRegistryScript<ReturnType<typeof use>, typeof GoogleAnalyticsOptions>(_options?.key || 'googleAnalytics', options => ({
    scriptInput: {
      src: withQuery('https://www.googletagmanager.com/gtag/js', { id: options?.id, l: options?.l }),
    },
    schema: import.meta.dev ? GoogleAnalyticsOptions : undefined,
    scriptOptions: {
      use: () => use(options),
      stub: import.meta.client ? undefined : ({ fn }) => { return fn === 'dataLayer' ? [] : void 0 },
      performanceMarkFeature: 'nuxt-third-parties-ga',
      ...({ tagPriority: 1 }),
    },
    // eslint-disable-next-line
        // @ts-ignore
    // eslint-disable-next-line
        clientInit: import.meta.server ? undefined : () => {window[options?.$1 ??  "dataLayer"]=window[options?.$1 ??  "dataLayer"]||[];window[options?.$1 ??  "dataLayer"].push({'js':new Date()});window[options?.$1 ??  "dataLayer"].push({'config':options?.$1 })},
  }), _options)
}
