import type { RegistryScript } from '#nuxt-scripts/types'
import type { ModuleOptions } from './module'
import { addTypeTemplate } from '@nuxt/kit'
import { hash } from 'ohash'

import { logger } from './logger'

const TRIGGER_PLACEHOLDER_RE = /"__TRIGGER_PLACEHOLDER__"/g

interface TypeTemplateContext {
  config: ModuleOptions
  newScripts: Required<RegistryScript>[]
}

export function registerTypeTemplates({ config, newScripts }: TypeTemplateContext) {
  // Type augmentations for existing modules (#app, #nuxt-scripts/types)
  addTypeTemplate({
    filename: 'types/nuxt-scripts-augments.d.ts',
    getContents: () => {
      const globalsKeys = Object.keys(config.globals || {})
      let augments = `// Generated by @nuxt/scripts
declare module '#app' {
  interface NuxtApp {
    $scripts: Record<${[...[...globalsKeys, ...Object.keys(config.registry || {})].map(k => `'${k}'`), ...['string']].join(' | ')}, import('#nuxt-scripts/types').UseScriptContext<any> | undefined>
    _scripts: Record<string, import('#nuxt-scripts/types').NuxtDevToolsScriptInstance>
  }
  interface RuntimeNuxtHooks {
    'scripts:updated': (ctx: { scripts: Record<string, import('#nuxt-scripts/types').NuxtDevToolsScriptInstance> }) => void | Promise<void>
    'scripts:globals': (globals: ${globalsKeys.length
      ? `{ ${globalsKeys.map(k => `${JSON.stringify(k)}: Record<string, any>`).join('; ')} }`
      : 'Record<string, Record<string, any>>'}) => void | Promise<void>
  }
}
${globalsKeys.length
  ? `declare module '@nuxt/schema' {
  interface PublicRuntimeConfig {
    scriptsGlobals?: {
${globalsKeys.map(k => `      ${JSON.stringify(k)}?: Record<string, any>`).join('\n')}
    }
  }
}
`
  : ''}`

      if (newScripts.length) {
        augments += `
declare module '#nuxt-scripts/types' {
  interface ScriptRegistry {
${newScripts.map((i) => {
  const key = i.import.name.replace('useScript', '')
  const keyLcFirst = key.substring(0, 1).toLowerCase() + key.substring(1)
  return `    ${keyLcFirst}?: import('${i.import.from}').${key}Input`
}).join('\n')}
  }
}
`
      }

      return `${augments}
export {}`
    },
  }, { nuxt: true })
}

export function templateTriggerResolver(defaultScriptOptions?: ModuleOptions['defaultScriptOptions']) {
  const needsIdleTimeout = defaultScriptOptions?.trigger && typeof defaultScriptOptions.trigger === 'object' && 'idleTimeout' in defaultScriptOptions.trigger
  const needsInteraction = defaultScriptOptions?.trigger && typeof defaultScriptOptions.trigger === 'object' && 'interaction' in defaultScriptOptions.trigger
  const needsServiceWorker = defaultScriptOptions?.trigger && typeof defaultScriptOptions.trigger === 'object' && 'serviceWorker' in defaultScriptOptions.trigger

  const imports = []
  if (needsIdleTimeout) {
    imports.push(`import { useScriptTriggerIdleTimeout } from '#nuxt-scripts/composables/useScriptTriggerIdleTimeout'`)
  }
  if (needsInteraction) {
    imports.push(`import { useScriptTriggerInteraction } from '#nuxt-scripts/composables/useScriptTriggerInteraction'`)
  }
  if (needsServiceWorker) {
    imports.push(`import { useScriptTriggerServiceWorker } from '#nuxt-scripts/composables/useScriptTriggerServiceWorker'`)
  }

  return [
    ...imports,
    `export function resolveTrigger(trigger) {`,
    needsIdleTimeout ? `  if ('idleTimeout' in trigger) return useScriptTriggerIdleTimeout({ timeout: trigger.idleTimeout })` : '',
    needsInteraction ? `  if ('interaction' in trigger) return useScriptTriggerInteraction({ events: trigger.interaction })` : '',
    needsServiceWorker ? `  if ('serviceWorker' in trigger) return useScriptTriggerServiceWorker()` : '',
    `  return null`,
    `}`,
  ].filter(Boolean).join('\n')
}

export function resolveTriggerForTemplate(trigger: any): string | null {
  if (trigger && typeof trigger === 'object') {
    const keys = Object.keys(trigger)
    if (keys.length > 1) {
      throw new Error(`Trigger object must have exactly one property, received: ${keys.join(', ')}`)
    }
    if ('idleTimeout' in trigger) {
      return `useScriptTriggerIdleTimeout({ timeout: ${trigger.idleTimeout} })`
    }
    if ('interaction' in trigger) {
      return `useScriptTriggerInteraction({ events: ${JSON.stringify(trigger.interaction)} })`
    }
    if ('serviceWorker' in trigger) {
      return `useScriptTriggerServiceWorker()`
    }
  }
  return null
}

export function templatePlugin(config: Partial<ModuleOptions>, registry: Required<RegistryScript>[]) {
  if (Array.isArray(config.globals)) {
    // convert to object
    config.globals = Object.fromEntries(config.globals.map(i => [hash(i), i]))
    logger.warn('The `globals` array option is deprecated. Convert to an object: `globals: { myScript: \'https://example.com/script.js\' }`')
  }
  const imports = []
  const inits = []
  // Globals are split out so the resolved inputs can be collected into a mutable map,
  // passed through the `scripts:globals` runtime hook, then registered.
  const globalMapEntries: string[] = []
  const globalInits: string[] = []
  const resolvedRegistryKeys: string[] = []
  let needsIdleTimeoutImport = false
  let needsInteractionImport = false

  let needsServiceWorkerImport = false

  // Registry entries are pre-normalized to [input, scriptOptions?] tuple form.
  // Only generate a global composable call when scriptOptions.trigger is present;
  // entries without a trigger are infrastructure only (proxy routes, types, bundling).
  for (const [k, c] of Object.entries(config.registry || {})) {
    if (c === false)
      continue
    const entry = c as unknown as [Record<string, any>, any?]
    const [, scriptOptions] = entry
    if (!scriptOptions?.trigger)
      continue
    const importDefinition = registry.find(i => i.import.name.toLowerCase() === `usescript${k.toLowerCase()}`)
    if (importDefinition) {
      resolvedRegistryKeys.push(k)
      imports.unshift(`import { ${importDefinition.import.name} } from '${importDefinition.import.from}'`)
      const [input] = entry
      const opts = { ...scriptOptions }
      const triggerResolved = resolveTriggerForTemplate(opts.trigger)
      if (triggerResolved) {
        opts.trigger = '__TRIGGER_PLACEHOLDER__' as any
        if (triggerResolved.includes('useScriptTriggerIdleTimeout'))
          needsIdleTimeoutImport = true
        if (triggerResolved.includes('useScriptTriggerInteraction'))
          needsInteractionImport = true
        if (triggerResolved.includes('useScriptTriggerServiceWorker'))
          needsServiceWorkerImport = true
      }
      const args = { ...input, scriptOptions: opts }
      const argsJson = triggerResolved
        ? JSON.stringify(args).replace(TRIGGER_PLACEHOLDER_RE, triggerResolved)
        : JSON.stringify(args)
      inits.push(`const ${k} = ${importDefinition.import.name}(${argsJson})`)
    }
  }
  // Globals input is merged at runtime so `runtimeConfig.public['nuxt-scripts'].globals[<key>]`
  // (set via env vars like NUXT_PUBLIC_NUXT_SCRIPTS_GLOBALS_<KEY>_<FIELD>) wins over
  // the build-time defaults. scriptOptions/object-triggers stay compile-time.
  const hasGlobals = Object.keys(config.globals || {}).length > 0
  for (const [k, c] of Object.entries(config.globals || {})) {
    let buildInput: Record<string, any>
    let extraOptions: Record<string, any> | undefined
    if (typeof c === 'string') {
      buildInput = { src: c }
    }
    else if (Array.isArray(c) && c.length === 2) {
      buildInput = typeof c[0] === 'string' ? { src: c[0] } : { ...(c[0] as any) }
      extraOptions = c[1] as any
    }
    else if (typeof c === 'object' && c !== null) {
      buildInput = { ...(c as any) }
    }
    else {
      continue
    }
    // Object-form triggers in the input bag need a placeholder substitution after JSON.stringify.
    const inputTrigger = buildInput.trigger
    const inputTriggerResolved = resolveTriggerForTemplate(inputTrigger)
    if (inputTriggerResolved)
      buildInput.trigger = '__TRIGGER_PLACEHOLDER__'
    let buildInputJson = JSON.stringify(buildInput)
    if (inputTriggerResolved)
      buildInputJson = buildInputJson.replace(TRIGGER_PLACEHOLDER_RE, inputTriggerResolved)
    const inputExpr = `Object.assign({ key: ${JSON.stringify(k)} }, ${buildInputJson}, __scriptsGlobals[${JSON.stringify(k)}] || {})`

    // scriptOptions trigger (array form, second slot) — same dance, separate JSON.
    let optionsJson = ''
    if (extraOptions && Object.keys(extraOptions).length > 0) {
      const optsCopy: Record<string, any> = { ...extraOptions }
      const optsTriggerResolved = resolveTriggerForTemplate(optsCopy.trigger)
      if (optsTriggerResolved)
        optsCopy.trigger = '__TRIGGER_PLACEHOLDER__'
      optionsJson = JSON.stringify(optsCopy)
      if (optsTriggerResolved)
        optionsJson = optionsJson.replace(TRIGGER_PLACEHOLDER_RE, optsTriggerResolved)
      if (optsTriggerResolved) {
        if (optsTriggerResolved.includes('useScriptTriggerIdleTimeout'))
          needsIdleTimeoutImport = true
        if (optsTriggerResolved.includes('useScriptTriggerInteraction'))
          needsInteractionImport = true
        if (optsTriggerResolved.includes('useScriptTriggerServiceWorker'))
          needsServiceWorkerImport = true
      }
    }
    if (inputTriggerResolved) {
      if (inputTriggerResolved.includes('useScriptTriggerIdleTimeout'))
        needsIdleTimeoutImport = true
      if (inputTriggerResolved.includes('useScriptTriggerInteraction'))
        needsInteractionImport = true
      if (inputTriggerResolved.includes('useScriptTriggerServiceWorker'))
        needsServiceWorkerImport = true
    }
    const useFn = `use: () => ({ ${k}: window.${k} })`
    const optionsArg = optionsJson ? `{ ...${optionsJson}, ${useFn} }` : `{ ${useFn} }`
    // Resolved input goes into the mutable `__globals` map keyed by its global key, so the
    // `scripts:globals` hook can rewrite/delete/add entries before registration.
    globalMapEntries.push(`${JSON.stringify(k)}: ${inputExpr}`)
    // Registration is guarded so a runtime override (env or hook) can disable an entry
    // per-instance (multi-tenant single-build): set `enabled: false` or an empty/null `src`
    // and the script is never registered. See https://github.com/nuxt/scripts/issues/759.
    globalInits.push(`const ${k} = __registerGlobal(__globals[${JSON.stringify(k)}], ${optionsArg})`)
  }
  // Add conditional imports for trigger composables
  const triggerImports = []
  if (needsIdleTimeoutImport) {
    triggerImports.push(`import { useScriptTriggerIdleTimeout } from '#nuxt-scripts/composables/useScriptTriggerIdleTimeout'`)
  }
  if (needsInteractionImport) {
    triggerImports.push(`import { useScriptTriggerInteraction } from '#nuxt-scripts/composables/useScriptTriggerInteraction'`)
  }
  if (needsServiceWorkerImport) {
    triggerImports.push(`import { useScriptTriggerServiceWorker } from '#nuxt-scripts/composables/useScriptTriggerServiceWorker'`)
  }

  const setupBody: string[] = []
  if (hasGlobals) {
    setupBody.push(`    const __scriptsGlobals = useRuntimeConfig().public.scriptsGlobals || {}`)
    // A global is skipped when the merged input disables it: `enabled === false`, or an
    // empty/null `src` (the env-overridable way to drop an unused integration per instance).
    setupBody.push(`    const __registerGlobal = (input, options) => { const { enabled, ...rest } = input; return (enabled === false || rest.src === '' || rest.src === null) ? undefined : useScript(rest, options) }`)
    // Resolved inputs (build-time default <- env override) collected into a mutable map.
    setupBody.push(`    const __globals = {`)
    setupBody.push(...globalMapEntries.map(e => `      ${e},`))
    setupBody.push(`    }`)
    // Runtime hook: userland may rewrite `src`/attrs, delete keys, or add new entries before
    // registration. Register the listener from an `enforce: 'pre'` plugin so it runs first.
    setupBody.push(`    await nuxtApp.hooks.callHook('scripts:globals', __globals)`)
    setupBody.push(...globalInits.map(i => `    ${i}`))
  }
  setupBody.push(...inits.map(i => `    ${i}`))
  setupBody.push(`    return { provide: { scripts: { ${[...Object.keys(config.globals || {}), ...resolvedRegistryKeys].join(', ')} } } }`)
  return [
    `import { useScript } from '#nuxt-scripts/composables/useScript'`,
    `import { defineNuxtPlugin${hasGlobals ? ', useRuntimeConfig' : ''} } from 'nuxt/app'`,
    ...triggerImports,
    ...imports,
    '',
    `export default defineNuxtPlugin({`,
    `  name: "scripts:init",`,
    `  env: { islands: false },`,
    `  parallel: true,`,
    `  ${hasGlobals ? 'async setup(nuxtApp) {' : 'setup() {'}`,
    ...setupBody,
    `  }`,
    `})`,
  ].join('\n')
}
