// Generated by scripts/generate-registry-types.ts — DO NOT EDIT
import { any, array, boolean, custom, literal, minLength, number, object, optional, pipe, record, string, union } from 'valibot'

// clarity
export const ClarityOptions = object({
  /**
   * The Clarity token.
   */
  id: pipe(string(), minLength(10)),
})

// cloudflare-web-analytics
export const CloudflareWebAnalyticsOptions = object({
  /**
   * The Cloudflare Web Analytics token.
   */
  token: pipe(string(), minLength(32)),
  /**
   * Cloudflare Web Analytics enables measuring SPAs automatically by overriding the History API’s pushState function
   * and listening to the onpopstate. Hash-based router is not supported.
   *
   * @default true
   */
  spa: optional(boolean()),
})

// crisp
export const CrispOptions = object({
  /**
   * The Crisp ID.
   */
  id: string(),
  /**
   * Extra configuration options. Used to configure the locale.
   * Same as CRISP_RUNTIME_CONFIG.
   * @see https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/language-customization/
   */
  runtimeConfig: optional(object({
    locale: optional(string()),
  })),
  /**
   * Associated a session, equivalent to using CRISP_TOKEN_ID variable.
   * Same as CRISP_TOKEN_ID.
   * @see https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/session-continuity/
   */
  tokenId: optional(string()),
  /**
   * Restrict the domain that the Crisp cookie is set on.
   * Same as CRISP_COOKIE_DOMAIN.
   * @see https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/cookie-policies/
   */
  cookieDomain: optional(string()),
  /**
   * The cookie expiry in seconds.
   * Same as CRISP_COOKIE_EXPIRATION.
   * @see https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/cookie-policies/#change-cookie-expiration-date
   */
  cookieExpiry: optional(number()),
})

// databuddy-analytics
export const DatabuddyAnalyticsOptions = object({
  // Required
  clientId: string(),

  // Advanced
  scriptUrl: optional(string()), // defaults to https://cdn.databuddy.cc/databuddy.js
  apiUrl: optional(string()), // defaults to https://basket.databuddy.cc
  disabled: optional(boolean()),

  // Core tracking (enabled by default by SDK)
  trackScreenViews: optional(boolean()),
  trackPerformance: optional(boolean()),
  trackSessions: optional(boolean()),

  // Optional tracking
  trackWebVitals: optional(boolean()),
  trackErrors: optional(boolean()),
  trackOutgoingLinks: optional(boolean()),
  trackScrollDepth: optional(boolean()),
  trackEngagement: optional(boolean()),
  trackInteractions: optional(boolean()),
  trackAttributes: optional(boolean()),
  trackHashChanges: optional(boolean()),
  trackExitIntent: optional(boolean()),
  trackBounceRate: optional(boolean()),

  // Performance options
  enableBatching: optional(boolean()),
  batchSize: optional(number()),
  batchTimeout: optional(number()),
  enableRetries: optional(boolean()),
  maxRetries: optional(number()),
  initialRetryDelay: optional(number()),
  samplingRate: optional(number()),

  // SDK metadata
  sdk: optional(string()),
  sdkVersion: optional(string()),

  // Observability & logging (accepted by SDK config)
  enableObservability: optional(boolean()),
  observabilityService: optional(string()),
  observabilityEnvironment: optional(string()),
  observabilityVersion: optional(string()),
  enableLogging: optional(boolean()),
  enableTracing: optional(boolean()),
  enableErrorTracking: optional(boolean()),
})

// fathom-analytics
export const FathomAnalyticsOptions = object({
  /**
   * The Fathom Analytics site ID.
   */
  site: string(),
  /**
   * The Fathom Analytics tracking mode.
   */
  spa: optional(union([literal('auto'), literal('history'), literal('hash')])),
  /**
   * Automatically track page views.
   */
  auto: optional(boolean()),
  /**
   * Enable canonical URL tracking.
   */
  canonical: optional(boolean()),
  /**
   * Honor Do Not Track requests.
   */
  honorDnt: optional(boolean()),
})

// google-adsense
export const GoogleAdsenseOptions = object({
  /**
   * The Google Adsense ID.
   */
  client: optional(string()),
  /**
   * Enable or disable Auto Ads.
   */
  autoAds: optional(boolean()),
})

// google-analytics
export const GoogleAnalyticsOptions = object({
  id: optional(string()), // The GA4 measurement ID (format: G-XXXXXXXX)
  l: optional(string()), // Optional global name for dataLayer (defaults to 'dataLayer')
})

// google-maps
export const GoogleMapsOptions = object({
  apiKey: string(),
  libraries: optional(array(string())),
  language: optional(string()),
  region: optional(string()),
  v: optional(union([literal('weekly'), literal('quarterly'), literal('beta'), literal('alpha'), string()])),
})

// google-recaptcha
export const GoogleRecaptchaOptions = object({
  siteKey: string(),
  // Use enterprise.js instead of api.js
  enterprise: optional(boolean()),
  // Use recaptcha.net (works in China)
  recaptchaNet: optional(boolean()),
  // Language code
  hl: optional(string()),
})

// google-sign-in
export const GoogleSignInOptions = object({
  clientId: string(),
  // Auto-select credentials if only one is available
  autoSelect: optional(boolean()),
  // Context for One Tap (signin, signup, or use)
  context: optional(union([literal('signin'), literal('signup'), literal('use')])),
  // FedCM API support (Privacy Sandbox) - mandatory from August 2025
  useFedcmForPrompt: optional(boolean()),
  // Cancel One Tap if user clicks outside
  cancelOnTapOutside: optional(boolean()),
  // UX mode: popup or redirect
  uxMode: optional(union([literal('popup'), literal('redirect')])),
  // Login URI for redirect flow
  loginUri: optional(string()),
  // ITP (Intelligent Tracking Prevention) support
  itpSupport: optional(boolean()),
  // Allowed parent origins for iframe embedding
  allowedParentOrigin: optional(union([string(), array(string())])),
  // Hosted domain - restrict to specific Google Workspace domain
  hd: optional(string()),
})

// google-tag-manager
export const GoogleTagManagerOptions = object({
  /** GTM container ID (format: GTM-XXXXXX) */
  id: string(),

  /** Optional dataLayer variable name */
  l: optional(string()),

  /** Authentication token for environment-specific container versions */
  auth: optional(string()),

  /** Preview environment name */
  preview: optional(string()),

  /** Forces GTM cookies to take precedence when true */
  cookiesWin: optional(union([boolean(), literal('x')])),

  /** Enables debug mode when true */
  debug: optional(union([boolean(), literal('x')])),

  /** No Personal Advertising - disables advertising features when true */
  npa: optional(union([boolean(), literal('1')])),

  /** Custom dataLayer name (alternative to "l" property) */
  dataLayer: optional(string()),

  /** Environment name for environment-specific container */
  envName: optional(string()),

  /** Referrer policy for analytics requests */
  authReferrerPolicy: optional(string()),

  /** Default consent settings for GTM */
  defaultConsent: optional(record(string(), union([string(), number()]))),
})

// hotjar
export const HotjarOptions = object({
  id: number(),
  sv: optional(number()),
})

// instagram-embed
export const InstagramEmbedOptions = object({
  /**
   * The Instagram post URL to embed
   * e.g., https://www.instagram.com/p/ABC123/
   */
  postUrl: string(),
  /**
   * Whether to include captions in the embed
   * @default true
   */
  captions: optional(boolean()),
  /**
   * Custom API endpoint for fetching embed HTML
   * @default '/api/_scripts/instagram-embed'
   */
  apiEndpoint: optional(string()),
})

// intercom
export const IntercomOptions = object({
  app_id: string(),
  api_base: optional(union([literal('https://api-iam.intercom.io'), literal('https://api-iam.eu.intercom.io'), literal('https://api-iam.au.intercom.io')])),
  name: optional(string()),
  email: optional(string()),
  user_id: optional(string()),
  // customizing the messenger
  alignment: optional(union([literal('left'), literal('right')])),
  horizontal_padding: optional(number()),
  vertical_padding: optional(number()),
})

// matomo-analytics
export const MatomoAnalyticsOptions = object({
  matomoUrl: optional(string()),
  siteId: optional(union([string(), number()])),
  cloudId: optional(string()),
  trackerUrl: optional(string()),
  trackPageView: optional(boolean()),
  enableLinkTracking: optional(boolean()),
  disableCookies: optional(boolean()),
  watch: optional(boolean()),
})

// meta-pixel
export const MetaPixelOptions = object({
  id: union([string(), number()]),
})

// npm
export const NpmOptions = object({
  packageName: string(),
  file: optional(string()),
  version: optional(string()),
  provider: optional(union([literal('jsdelivr'), literal('cdnjs'), literal('unpkg')])),
})

// paypal
export const PayPalOptions = object({
  clientId: string(),
  buyerCountry: optional(string()),
  commit: optional(string()),
  components: optional(union([string(), array(string())])),
  currency: optional(string()),
  debug: optional(union([string(), boolean()])),
  disableFunding: optional(union([string(), array(string())])),
  enableFunding: optional(union([string(), array(string())])),
  integrationDate: optional(string()),
  intent: optional(string()),
  locale: optional(string()),
  /**
   * loadScript() supports an array for merchantId, even though
   * merchant-id technically may not contain multiple values.
   * For an array with a length of > 1 it automatically sets
   * merchantId to "*" and moves the actual values to dataMerchantId
   */
  merchantId: optional(union([string(), array(string())])),
  partnerAttributionId: optional(string()),
  vault: optional(union([string(), boolean()])),
  // own props
  sandbox: optional(boolean()),
})

// posthog
export const PostHogOptions = object({
  apiKey: string(),
  region: optional(union([literal('us'), literal('eu')])),
  apiHost: optional(string()),
  autocapture: optional(boolean()),
  capturePageview: optional(union([boolean(), literal('history_change')])),
  capturePageleave: optional(boolean()),
  disableSessionRecording: optional(boolean()),
  config: optional(record(string(), any())),
})

// reddit-pixel
export const RedditPixelOptions = object({
  id: string(),
})

// rybbit-analytics
export const RybbitAnalyticsOptions = object({
  siteId: union([string(), number()]), // required
  autoTrackPageview: optional(boolean()),
  trackSpa: optional(boolean()),
  trackQuery: optional(boolean()),
  trackOutbound: optional(boolean()),
  trackErrors: optional(boolean()),
  sessionReplay: optional(boolean()),
  webVitals: optional(boolean()),
  skipPatterns: optional(array(string())),
  maskPatterns: optional(array(string())),
  debounce: optional(number()),
  apiKey: optional(string()),
})

// segment
export const SegmentOptions = object({
  writeKey: string(),
  analyticsKey: optional(string()),
})

// snapchat-pixel
export const InitObjectPropertiesSchema = object({
  user_email: optional(string()),
  ip_address: optional(string()),
  user_phone_number: optional(string()),
  user_hashed_email: optional(string()),
  user_hashed_phone_number: optional(string()),
  firstname: optional(string()),
  lastname: optional(string()),
  geo_city: optional(string()),
  geo_region: optional(string()),
  geo_postal_code: optional(string()),
  geo_country: optional(string()),
  age: optional(string()),
})
export const SnapTrPixelOptions = object({
  id: string(),
  trackPageView: optional(boolean()),
  ...(InitObjectPropertiesSchema?.entries || {}),
})

// stripe
export const StripeOptions = object({
  advancedFraudSignals: optional(boolean()),
})

// tiktok-pixel
export const TikTokPixelOptions = object({
  id: string(),
  trackPageView: optional(boolean()), // default true
})

// umami-analytics
export const UmamiAnalyticsOptions = object({
  websiteId: string(), // required
  /**
   * By default, Umami will send data to wherever the script is located.
   * You can override this to send data to another location.
   */
  hostUrl: optional(string()),
  /**
   * By default, Umami tracks all pageviews and events for you automatically.
   * You can disable this behavior and track events yourself using the tracker functions.
   * https://umami.is/docs/tracker-functions
   */
  autoTrack: optional(boolean()),
  /**
   * If you want the tracker to only run on specific domains, you can add them to your tracker script.
   * This is a comma delimited list of domain names.
   * Helps if you are working in a staging/development environment.
   */
  domains: optional(array(string())),
  /**
   * If you want the tracker to collect events under a specific tag.
   * Events can be filtered in the dashboard by a specific tag.
   */
  tag: optional(string()),
  /**
   * Function that will be called before data is sent to Umami.
   * The function takes two parameters: type and payload.
   * Return the payload to continue sending, or return a falsy value to cancel.
   */
  beforeSend: optional(union([
    custom<(type: string, payload: Record<string, any>) => Record<string, any> | null | false>(input => typeof input === 'function'),
    string(),
  ])),
})

// x-embed
export const XEmbedOptions = object({
  /**
   * The tweet ID to embed
   */
  tweetId: string(),
  /**
   * Optional: Custom API endpoint for fetching tweet data
   * @default '/api/_scripts/x-embed'
   */
  apiEndpoint: optional(string()),
  /**
   * Optional: Custom image proxy endpoint
   * @default '/api/_scripts/x-embed-image'
   */
  imageProxyEndpoint: optional(string()),
})

// x-pixel
export const XPixelOptions = object({
  id: string(),
  version: optional(string()),
})
