import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { resolveProxySecret } from '../../packages/script/src/module'

const ENV_KEY = 'NUXT_SCRIPTS_PROXY_SECRET'

describe('resolveProxySecret', () => {
  let testDir: string
  let savedEnv: string | undefined

  beforeEach(() => {
    testDir = join(tmpdir(), `nuxt-scripts-test-${Date.now()}`)
    mkdirSync(testDir, { recursive: true })
    savedEnv = process.env[ENV_KEY]
    delete process.env[ENV_KEY]
  })

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true })
    if (savedEnv !== undefined)
      process.env[ENV_KEY] = savedEnv
    else
      delete process.env[ENV_KEY]
  })

  it('returns config secret with highest priority', async () => {
    process.env[ENV_KEY] = 'env-secret'
    const result = await resolveProxySecret(testDir, true, 'config-secret')
    expect(result).toEqual({ secret: 'config-secret', ephemeral: false, source: 'config' })
  })

  it('falls back to env var when no config secret', async () => {
    process.env[ENV_KEY] = 'env-secret'
    const result = await resolveProxySecret(testDir, true)
    expect(result).toEqual({ secret: 'env-secret', ephemeral: false, source: 'env' })
  })

  it('returns undefined in prod when no secret is available', async () => {
    const result = await resolveProxySecret(testDir, false)
    expect(result).toBeUndefined()
  })

  it('returns undefined when autoGenerate is false even in dev', async () => {
    const result = await resolveProxySecret(testDir, true, undefined, false)
    expect(result).toBeUndefined()
  })

  it('auto-generates and writes to .env in dev when file does not exist', async () => {
    const result = await resolveProxySecret(testDir, true)
    expect(result).toBeDefined()
    expect(result!.source).toBe('dotenv-generated')
    expect(result!.ephemeral).toBe(false)
    expect(result!.secret).toHaveLength(64) // 32 bytes hex

    const envContent = readFileSync(join(testDir, '.env'), 'utf-8')
    expect(envContent).toContain(`${ENV_KEY}=${result!.secret}`)
    expect(envContent).toContain('# Generated by @nuxt/scripts')
  })

  it('appends to existing .env in dev', async () => {
    writeFileSync(join(testDir, '.env'), 'OTHER_VAR=value\n')
    const result = await resolveProxySecret(testDir, true)
    expect(result!.source).toBe('dotenv-generated')

    const envContent = readFileSync(join(testDir, '.env'), 'utf-8')
    expect(envContent).toContain('OTHER_VAR=value')
    expect(envContent).toContain(`${ENV_KEY}=`)
  })

  it('returns existing secret from .env without generating a new one', async () => {
    writeFileSync(join(testDir, '.env'), `${ENV_KEY}=existing-secret-value\n`)
    const result = await resolveProxySecret(testDir, true)
    expect(result).toEqual({ secret: 'existing-secret-value', ephemeral: false, source: 'dotenv-generated' })

    // Should not have written a second line
    const envContent = readFileSync(join(testDir, '.env'), 'utf-8')
    const matches = envContent.match(new RegExp(ENV_KEY, 'g'))
    expect(matches).toHaveLength(1)
  })

  it('waits for another process to persist the secret while its lock is held', async () => {
    const envPath = join(testDir, '.env')
    const lockPath = `${envPath}.nuxt-scripts.lock`
    writeFileSync(lockPath, '')

    const persisted = new Promise<void>((resolve) => {
      setTimeout(() => {
        writeFileSync(envPath, `${ENV_KEY}=shared-process-secret\n`)
        rmSync(lockPath)
        resolve()
      }, 20)
    })

    const result = await resolveProxySecret(testDir, true)
    await persisted

    expect(result).toEqual({ secret: 'shared-process-secret', ephemeral: false, source: 'dotenv-generated' })
  })

  it('replaces an empty persisted secret instead of returning an ephemeral value', async () => {
    writeFileSync(join(testDir, '.env'), `${ENV_KEY}=\n`)

    const result = await resolveProxySecret(testDir, true)

    expect(result?.source).toBe('dotenv-generated')
    expect(result?.secret).toHaveLength(64)
    expect(readFileSync(join(testDir, '.env'), 'utf-8')).toBe(`${ENV_KEY}=${result?.secret}\n`)
  })

  it('replaces a whitespace-only persisted secret', async () => {
    writeFileSync(join(testDir, '.env'), `${ENV_KEY}=   \n`)

    const result = await resolveProxySecret(testDir, true)

    expect(result?.source).toBe('dotenv-generated')
    expect(result?.secret).toHaveLength(64)
    expect(readFileSync(join(testDir, '.env'), 'utf-8')).toBe(`${ENV_KEY}=${result?.secret}\n`)
  })

  it('populates process.env after generating a new secret', async () => {
    await resolveProxySecret(testDir, true)
    expect(process.env[ENV_KEY]).toBeDefined()
    expect(process.env[ENV_KEY]).toHaveLength(64)
  })

  it('falls back to in-memory when .env dir is read-only', async () => {
    // Use a non-existent deeply nested path that can't be written
    const result = await resolveProxySecret('/proc/nonexistent/path', true)
    expect(result).toBeDefined()
    expect(result!.source).toBe('memory-generated')
    expect(result!.ephemeral).toBe(true)
    expect(result!.secret).toHaveLength(64)
  })

  it('adds newline before appending when .env does not end with newline', async () => {
    writeFileSync(join(testDir, '.env'), 'OTHER_VAR=value')
    await resolveProxySecret(testDir, true)
    const envContent = readFileSync(join(testDir, '.env'), 'utf-8')
    // Should have a newline between existing content and new key
    expect(envContent).toMatch(/value\n.*NUXT_SCRIPTS_PROXY_SECRET=/)
  })
})
