import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { resolveProxySecret } from '../../packages/script/src/module'

const ENV_KEY = 'NUXT_SCRIPTS_PROXY_SECRET'

describe('resolveProxySecret', () => {
  let testDir: string
  let savedEnv: string | undefined

  beforeEach(() => {
    testDir = join(tmpdir(), `nuxt-scripts-test-${Date.now()}`)
    mkdirSync(testDir, { recursive: true })
    savedEnv = process.env[ENV_KEY]
    delete process.env[ENV_KEY]
  })

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true })
    if (savedEnv !== undefined)
      process.env[ENV_KEY] = savedEnv
    else
      delete process.env[ENV_KEY]
  })

  it('returns config secret with highest priority', () => {
    process.env[ENV_KEY] = 'env-secret'
    const result = resolveProxySecret(testDir, true, 'config-secret')
    expect(result).toEqual({ secret: 'config-secret', ephemeral: false, source: 'config' })
  })

  it('falls back to env var when no config secret', () => {
    process.env[ENV_KEY] = 'env-secret'
    const result = resolveProxySecret(testDir, true)
    expect(result).toEqual({ secret: 'env-secret', ephemeral: false, source: 'env' })
  })

  it('returns undefined in prod when no secret is available', () => {
    const result = resolveProxySecret(testDir, false)
    expect(result).toBeUndefined()
  })

  it('returns undefined when autoGenerate is false even in dev', () => {
    const result = resolveProxySecret(testDir, true, undefined, false)
    expect(result).toBeUndefined()
  })

  it('auto-generates and writes to .env in dev when file does not exist', () => {
    const result = resolveProxySecret(testDir, true)
    expect(result).toBeDefined()
    expect(result!.source).toBe('dotenv-generated')
    expect(result!.ephemeral).toBe(false)
    expect(result!.secret).toHaveLength(64) // 32 bytes hex

    const envContent = readFileSync(join(testDir, '.env'), 'utf-8')
    expect(envContent).toContain(`${ENV_KEY}=${result!.secret}`)
    expect(envContent).toContain('# Generated by @nuxt/scripts')
  })

  it('appends to existing .env in dev', () => {
    writeFileSync(join(testDir, '.env'), 'OTHER_VAR=value\n')
    const result = resolveProxySecret(testDir, true)
    expect(result!.source).toBe('dotenv-generated')

    const envContent = readFileSync(join(testDir, '.env'), 'utf-8')
    expect(envContent).toContain('OTHER_VAR=value')
    expect(envContent).toContain(`${ENV_KEY}=`)
  })

  it('returns existing secret from .env without generating a new one', () => {
    writeFileSync(join(testDir, '.env'), `${ENV_KEY}=existing-secret-value\n`)
    const result = resolveProxySecret(testDir, true)
    expect(result).toEqual({ secret: 'existing-secret-value', ephemeral: false, source: 'dotenv-generated' })

    // Should not have written a second line
    const envContent = readFileSync(join(testDir, '.env'), 'utf-8')
    const matches = envContent.match(new RegExp(ENV_KEY, 'g'))
    expect(matches).toHaveLength(1)
  })

  it('populates process.env after generating a new secret', () => {
    resolveProxySecret(testDir, true)
    expect(process.env[ENV_KEY]).toBeDefined()
    expect(process.env[ENV_KEY]).toHaveLength(64)
  })

  it('falls back to in-memory when .env dir is read-only', () => {
    // Use a non-existent deeply nested path that can't be written
    const result = resolveProxySecret('/proc/nonexistent/path', true)
    expect(result).toBeDefined()
    expect(result!.source).toBe('memory-generated')
    expect(result!.ephemeral).toBe(true)
    expect(result!.secret).toHaveLength(64)
  })

  it('adds newline before appending when .env does not end with newline', () => {
    writeFileSync(join(testDir, '.env'), 'OTHER_VAR=value')
    resolveProxySecret(testDir, true)
    const envContent = readFileSync(join(testDir, '.env'), 'utf-8')
    // Should have a newline between existing content and new key
    expect(envContent).toMatch(/value\n.*NUXT_SCRIPTS_PROXY_SECRET=/)
  })
})
