name: Nightly

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '!**'

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm dlx pkg-pr-new publish
