name: release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'nuxt' && github.event_name == 'push' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.15.2
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install

      - name: Prepare build environment
        run: pnpm dev:prepare

      - name: nightly release
        run: pnpm changelogen --canary nightly --publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
