name: release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'nuxt' && github.event_name == 'push' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-node@4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Prepare build environment
        run: pnpm dev:prepare

      - name: nightly release
        run: pnpm changelogen --canary nightly --publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
